# Generated by Django 5.2.4 on 2025-08-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('seat_type', models.CharField(blank=True, max_length=50)),
                ('category_allotment', models.CharField(blank=True, max_length=50)),
                ('anti_ragging_ref', models.CharField(blank=True, max_length=50)),
                ('correspondence_address', models.TextField()),
                ('correspondence_pin', models.CharField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_cell', models.CharField(max_length=15)),
                ('permanent_address', models.TextField()),
                ('permanent_pin', models.CharField(max_length=10)),
                ('father_cell', models.CharField(max_length=15)),
                ('mother_cell', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('birth_place', models.CharField(max_length=50)),
                ('birth_district', models.CharField(max_length=50)),
                ('birth_state', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('father_fullname', models.CharField(max_length=100)),
                ('father_office_address', models.TextField(blank=True)),
                ('father_designation', models.CharField(blank=True, max_length=100)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('father_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mother_fullname', models.CharField(max_length=100)),
                ('mother_office_address', models.TextField(blank=True)),
                ('mother_designation', models.CharField(blank=True, max_length=100)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('mother_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('name_hsc', models.CharField(max_length=100)),
                ('hsc_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('x_passing_month_year', models.CharField(max_length=10)),
                ('x_school', models.CharField(max_length=150)),
                ('x_board', models.CharField(max_length=100)),
                ('xii_passing_month_year', models.CharField(max_length=10)),
                ('xii_school', models.CharField(max_length=150)),
                ('xii_board', models.CharField(max_length=100)),
                ('mhtcet_rollno', models.CharField(max_length=20)),
                ('state_merit_no', models.CharField(max_length=20)),
                ('mhtcet_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('application_id', models.CharField(max_length=20)),
                ('xii_phy', models.FloatField()),
                ('xii_chem', models.FloatField()),
                ('xii_math', models.FloatField()),
                ('qualifying_phy', models.FloatField()),
                ('qualifying_chem', models.FloatField()),
                ('qualifying_math', models.FloatField()),
                ('ssc_agg', models.FloatField()),
                ('ssc_outof', models.FloatField()),
                ('ssc_percentage', models.FloatField()),
                ('ssc_math', models.FloatField()),
                ('ssc_math_outof', models.FloatField()),
                ('ssc_math_percentage', models.FloatField()),
                ('hsc_agg', models.FloatField()),
                ('hsc_outof', models.FloatField()),
                ('hsc_percentage', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cap_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
