# Generated by Django 5.2.4 on 2025-08-06 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYearAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=100)),
                ('correspondence_address', models.TextField()),
                ('student_cell_no', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('father_cell_no', models.CharField(max_length=15)),
                ('dob_day', models.PositiveSmallIntegerField()),
                ('dob_month', models.PositiveSmallIntegerField()),
                ('dob_year', models.PositiveSmallIntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('mht_cet_percentile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('state_merit_no', models.CharField(max_length=50)),
                ('application_id', models.CharField(max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_year_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondYearAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=100)),
                ('correspondence_address', models.TextField()),
                ('student_cell_no', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('father_cell_no', models.CharField(max_length=15)),
                ('dob_day', models.PositiveSmallIntegerField()),
                ('dob_month', models.PositiveSmallIntegerField()),
                ('dob_year', models.PositiveSmallIntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('passed_diploma_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma_passing_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('application_id', models.CharField(max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_year_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CapApplication',
        ),
    ]
