# Generated by Django 5.2.4 on 2025-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0002_firstyearadmission_secondyearadmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstyearadmission',
            name='mht_cet_percentile',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='secondyearadmission',
            name='diploma_passing_percentage',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
